### ISSUE TITLE
uninitialized stream (IOError)

### ISSUE THREAD

**Issue by eforrer** [digital-fabric/polyphony#27]
When using `polyphony` and `concurrent-ruby` version `1.1.5`. The `net/http`, `faraday` and `httparty` fails and raise:

```
ruby/2.7.1/lib/ruby/2.7.0/net/http.rb:1001:in `nonblock=': uninitialized stream (IOError)
```

When I upgrade `concurrent-ruby` to version `1.1.6` the problem with `faraday` and `httparty` gets fixed, but  the script  gets stuck in the request or something and it does not finish.

Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "httparty", "~> 0.18.1"

# gem "faraday", "~> 1.0"

gem "concurrent-ruby", "~> 1.1.6"

gem "polyphony", "~> 0.43.4"
```

e.g. script.

```ruby
Bundler.require(:default, :development)
require 'uri'
require 'net/http'

data = ::Concurrent::Array.new
urls = [
  'http://realiteq.net/?q=time'
]

def get_time(url)
  uri = URI(url)
  response = Net::HTTP.get(uri)
end

urls.each_slice(1) do |links|
  links.each do |link|
    fibers = ::Concurrent::Array.new
    puts " #{link}"
    fibers << spin do
      data << get_time(link)
    end
    Fiber.await(*fibers)
  end
end

puts "Finished"
```

**Environment**

* ruby
  * `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]`
* OS
  * `Linux kali 5.6.0-kali2-amd64 #1 SMP Debian 5.6.14-2kali1 (2020-06-10) x86_64 GNU/Linux`
* OpenSSL
  * `OpenSSL 1.1.1g  21 Apr 2020`

**Comment by ciconia** [comment]
There are a number of issues at play here:

- I fixed the exception you were experiencing, please upgrade to Polyphony 0.43.5.
- In order to prevent your script from hanging, make sure to `require 'polyphony'` before any other library (except for bundler). If you use `Bundler.require` you'll run into problems.
- There's no reason to use `Concurrent::Array`. Note that basically all constructs in concurrent-ruby are made with threads in mind. When using Polyphony there's absolutely no need to use such thread-safe constructs, since you're basically running on a single thread. Besides, I do not intend to support integrating Polyphony with concurrent-ruby any further than the absolute minimum.
- Note that instead of collecting fibers into an array and calling `Fiber.await`, you can instead call `Fiber.current.await_all_children` which will have the same effect (yes, the documentation still needs a lot of work).

**Comment by eforrer** [comment]
Thanks @ciconia  for all you tips!.

I upgraded the gem and made some changes to the script but the issue still persists, it only works for the  url that I posted on the issue. If try with another URL I get the same exceptions.

Here is the example with the changes:

```ruby
require 'polyphony'
require 'concurrent'
require 'uri'
require 'net/http'


data = ::Concurrent::Array.new
urls = [
  "http://realiteq.net/?q=time",
  "https://philippmuens.com/logistic-regression-from-scratch/",
  "https://tmikey.tech/tech_daily/2019/08/08/one_click_sound_switch.html",
  "https://superuser.com/questions/919033/quickly-change-audio-device-in-kde",
  "https://www.scrapingbee.com/blog/web-scraping-ruby/",
  "https://dennisbeatty.com/2019/01/09/cool-clis-in-elixir-with-io-write-2.html",
  "https://elixir-lang.org/blog/2020/06/23/growing-with-elixir-at-brex/",
  "http://elixirstatus.com/p/upvN-deploying-elixir-to-aws-with-tarraform-and-ansible",
  "https://weblog.rubyonrails.org/2020/6/17/Rails-6-0-3-2-has-been-released/",
  "https://www.clever-cloud.com/blog/engineering/2020/06/09/deploy-elixir-phoenix/",
  "https://github.com/comma-csv/comma",
  "https://elixirforum.com/t/introducing-mechanize-for-elixir-web-site-interaction-automation-library/32647",
  "http://elixirstatus.com/p/KNSq-finite-state-machines-library-with-opt-in-ecto-friendliness",
  "https://boringrails.com/articles/hovercards-stimulus/",
  "http://elixirstatus.com/p/YSEn-decomposing-domain-models-based-on-lifecycles",
  "http://elixirstatus.com/p/hFv4-step-by-step-guide-to-improving-cohesion-in-elixir",
  "https://dev.to/ericdouglas/uncomfortable-question-001-3o1o",
  "https://elixirforum.com/t/multiple-matches-inside-reduce/32629",
  "https://elixirforum.com/t/video-transport-over-erlang-elixir/32623",
  "https://hex.pm/packages/incident",
  "https://github.com/Qqwy/elixir-blocked",
  "https://hex.pm/packages/domo",
  "https://github.com/wanderanimrod/elixir_mock",
  "https://patrykbak.com/2020/04/15/should-you-use-database-transactions-for-data-consistency.html",
  "https://dev.to/ericdouglas/the-beauty-of-recursion-and-pattern-matching-in-functional-programming-languages-hmn",
  "https://morphic.pro/posts/how-i-added-pagination-using-live-patch-for-my-liveview-site-using-dissolver"
  ]

def get_data(url)
  uri = URI(url)
  response = Net::HTTP.get_response(uri)
  body = response.body
  body
end

urls.each_slice(1) do |links|
  links.each do |link|
    puts " #{link}"
    spin do
      data << get_data(link)
    end
    Fiber.current.await_all_children
  end
end

puts "Finished - (#{data.length}) links"
```

Thanks

**Comment by ciconia** [comment]
I'm investigating...

**Comment by ciconia** [comment]
I'm going to handle this in #28.

**Comment by ciconia** [comment]
@eforrer this issue is fixed in #28. Please upgrade to Polyphony 0.43.6 and try again. Your script should work now.

**Comment by eforrer** [comment]
Just confirming that it works now.

Great work, thanks a lot!
